name: Build Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.18.0'

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: Install Ionic CLI
      run: npm install -g @ionic/cli

    - name: Install Capacitor CLI
      run: npm install @capacitor/core @capacitor/cli

    - name: Build Ionic project
      run: npm run build

    - name: Prepare Android platform
      run: npx cap sync android

    - name: Create placeholder cordova.variables.gradle
      run: |
        mkdir -p android/capacitor-cordova-android-plugins
        touch android/capacitor-cordova-android-plugins/cordova.variables.gradle

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
