name: Build iOS App

on:
  push:
    branches:
      - Sprint2406
  pull_request:
    branches:
      - Sprint2406

jobs:
  build:
    runs-on: macos-latest  # Use the macOS runner for iOS builds

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode_13.app  
        sudo xcodebuild -runFirstLaunch

    - name: Install Cocoapods (if needed)
      run: |
        gem install cocoapods
        pod install --project-directory=ios/App  

    - name: Build iOS app
      run: |
        xcodebuild -workspace ios/App/App.xcworkspace \
                   -scheme App \
                   -destination 'generic/platform=iOS' \
                   -configuration Release \
                   build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Archive the app
      run: |
        xcodebuild -workspace ios/App/App.xcworkspace \
                   -scheme App \
                   -destination 'generic/platform=iOS' \
                   -configuration Release \
                   archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
                   -archivePath build/App.xcarchive

    - name: Export IPA (Optional)
      run: |
        xcodebuild -exportArchive \
                   -archivePath build/App.xcarchive \
                   -exportOptionsPlist ios/App/exportOptions.plist \
                   -exportPath build \
                   CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Upload IPA artifact (Optional)
      uses: actions/upload-artifact@v2
      if: success() && github.event_name == 'push'
      with:
        name: app-ipa
        path: build/*.ipa
